01mf02/jaq

jaq/Cargo.toml

https://github.com/01mf02/jaq/blob/main/jaq/src/main.rs#L249

jaq requires rust >= 1.59

---

jaq-std/src/std.jq
jaq-std/tests/std.rs

This adds the `while` command from jq's standard library.
```
$ ./target/debug/jaq '[ while(. < 100; . * 2) ]' <<< 1
[
1,
2,
4,
8,
16,
32,
64
]
```

Add while to standard library

---

jaq-core/src/lib.rs

Hey! I'm planning on using `jaq_core` to have embedded JQ-style syntax in my widget system [eww](https://github.com/elkowar/eww).
As the filters are gonna be ran several times, I'd want to cache the generated filters in between runs. For this, the filter struct needs to be clone!

Make Filter struct Clone

---

jaq-core/src/error.rs
jaq-core/src/filter.rs
jaq-core/src/lib.rs
jaq-core/tests/custom.rs

Introduces the `CustomFilter` type and a new method `Definitions.insert_custom(name, filter)`. Custom filters can be constructed from an arity, a run function, and an optional update function. If no update function is provided, the filter cannot be used like `filter |= ...`.
No particular care is taken to make writing filters ergonomic, but it's fairly straightforward nonetheless. For example, here's a basic sqrt:
```rust
defs.insert_custom("sqrt", CustomFilter::new(0, |_, (_, val)| {
Box::new(std::iter::once(match val {
Val::Float(f) => Ok(Val::Float(f.sqrt())),
_ => Err(jaq_core::Error::Custom(format!("sqrt: expected float, got {val:?}"))),
}))
}));
```
Also:
- Adds Clone derive (and Debug, Default) to `Definitions` so it's easier to use in tests to call multiple times.
- Adds two new …

Custom filters

---

jaq-parse/src/token.rs

`1e-1` and `1e+1` in filters are now parsed correctly.
closes #79

Handle number exponents with signs in filter

---

jaq-core/src/filter.rs
jaq-core/tests/named.rs
jaq-core/tests/tests.rs
jaq-std/src/std.jq
jaq-std/tests/std.rs

To match jq, rename `keys` to `keys_unsorted` and implement `keys` as a std filter based on `keys_unsorted`. `keys` now returns the array of keys sorted

Add keys_unsorted

---

README.md
jaq-core/src/error.rs
jaq-core/src/filter.rs
jaq-core/src/val.rs
jaq-core/tests/named.rs

For jq parity, adds byte-length function for strings.

Implement utf8bytelength function

---

README.md
jaq-core/src/error.rs
jaq-core/src/filter.rs
jaq-core/src/val.rs
jaq-core/tests/named.rs

Adds all (AFAICT) of the missing string functions:
* `startswith`
* `endswith`
* `ltrimstr`
* `rtrimstr`

Imeplement string functions

---

jaq-core/src/val.rs
jaq-core/tests/tests.rs

Feature Addition - 
`str * int` will result in a string that is repeated `int` times
If int is negative or zero, resulting value will be `null`.

Implemented str * int operations

---

jaq/src/main.rs

For compatibility with jq's upcoming release.
Introduced to jq in https://github.com/jqlang/jq/pull/1990
Note that JSON can contain NUL characters (e.g. `"\u0000"`), so it is not possible to distinguish separate values in every case, even when using this flag

Implement --nul-output

---

jaq/src/main.rs

For compatibility with jq's upcoming (1.7?) release.
Introduced into jq with https://github.com/jqlang/jq/pull/2654, when using --exit-status, parse errors now cause jq to exit with status code 5 (`JQ_ERROR_UNKNOWN`) instead of 4 (`JQ_OK_NO_OUTPUT`). The motivation is to be able to distinguish the no-output case from parsing errors.
Mirroring this, 5 will be used for both `Error::Jaq` and `Error::Parse`, i.e. both filter parsing errors and JSON parsing errors.

Match jq exit code for no output with --exit-status

---

jaq-std/src/std.jq
jaq-std/tests/std.rs

For compatibility with jq, alias
`todate` -> `todateiso8601`
and
`fromdate` -> `fromdateiso8601`
closes #58

add aliases for date funcs

---

.github/workflows/rust.yml
jaq-core/src/lib.rs
jaq-native/src/lib.rs

This PR adds a clippy step to the CI workflow, and fixes the current clippy warnings.
Relevant: <https://github.com/rust-lang/rust-clippy/issues/1209>

Feature/clippy in CI

---

.github/workflows/release.yml

This workflow compiles binaries for different architectures and uploads them to a new release draft.
It is triggered when tagging a commit with a tag starting with `v[0-9]`.

Release workflow.

---

jaq-interpret/src/lir.rs
jaq-interpret/src/mir.rs
jaq-parse/src/filter.rs
jaq-std/src/std.jq
jaq-syn/src/filter.rs

Quoth the jq manual:
> if A then B end is the same as if A then B else . end. That is, the else branch is optional, and if absent is the same as .. This also applies to elif with absent ending else branch.

Make `else` branch optional

---

jaq/src/main.rs

Reverts 01mf02/jaq#91, because of #101.

Revert "Implement --nul-output"

---

jaq-std/src/std.jq
jaq-std/tests/std.rs

0d402245692e8f2a5f52fcb48297ecc89caeaa02 broke the branching behaviour of `sub`.
This PR restores it, and adds a test to ensure it does not fail again.

Restore `sub` branching

---

README.md
jaq-interpret/src/filter.rs
jaq-interpret/src/lib.rs
jaq-interpret/src/lir.rs
jaq-interpret/src/mir.rs
jaq-interpret/tests/tests.rs
jaq-parse/src/def.rs
jaq-parse/src/filter.rs
jaq-parse/src/lib.rs
jaq-parse/src/path.rs
jaq-parse/src/string.rs
jaq-parse/src/token.rs
jaq-std/build.rs
jaq-syn/src/def.rs
jaq-syn/src/filter.rs
jaq-syn/src/lib.rs
jaq-syn/src/path.rs
jaq-syn/src/string.rs

This PR adds support for string interpolation, such as `"The successor of \(.) is \(.+1)."`
It also allows prefixing formatters, allowing for things like `@uri "https://www.google.com/search?q=\(.search)"`.
Unlike jq, jaq allows the definition of n-ary filters starting with an `@`.
However, like jq, jaq limits the usage of formatters usable in string interpolation to nullary filters starting with an `@`. This restriction simplifies the parser, which might otherwise run into exponential runtime issues.

String interpolation

---

jaq-core/tests/tests.rs
jaq-interpret/src/box_iter.rs
jaq-interpret/src/filter.rs
jaq-interpret/src/lib.rs
jaq-interpret/src/results.rs

This PR makes the evaluation of cartesian products lazy in both arguments.
Previously, only the left-hand side of binary filters (such as addition) were evaluated lazily. As a consequence,
~~~ jq
limit(3; recurse(.+1) + 0)
~~~
would terminate, but
~~~ jq
limit(3; 0 + recurse(.+1))
~~~
would not. With this PR, both variants terminate.
As a downside, the results of the right-hand side are not cached anymore.
That is, `(0, 1) + expensive_f` will now evaluate `expensive_f` twice, whereas it was only evaluated once before.
However, I suppose that the impact of this is minimal, because few people would use multiple inputs in conjunction with "expensive" functions as arguments to binary operators.

Lazy cartesian products

---

jaq-interpret/src/lib.rs
jaq-interpret/src/rc_list.rs

This PR makes reference-counted lists clonable without cloning any of its elements.
Reference-counted lists are used to store the contents of bound variables in jaq.
As they are part of the filter execution context, they are very frequently cloned.
So far, cloning such a list would always clone the head of list, in addition to cloning an `Rc`-pointer to the tail of the list.
After this change, cloning only clones an `Rc`-pointer to the list.
The performance implication of this change is quite favourable:
|Benchmark|n|Before|After|
|---|--:|--:|--:|
|`empty`|512|**630**|650
|`bf-fib`|13|400|**380**
|`reverse`|1048576|**30**|**30**
|`sort`|1048576|**100**|**100**
|`group-by`|1048576|440|**390**
|`min-max`|1048576|**180**|**180**
|`add`|1048576|460|**420**
|`kv`|131072|**140**|150 …

Make Rc lists clonable without cloning any of its elements.

---

jaq-core/tests/tests.rs
jaq-interpret/src/filter.rs
jaq-interpret/src/lib.rs
jaq-interpret/src/lir.rs
jaq-interpret/src/mir.rs
jaq-interpret/tests/path.rs
jaq-interpret/tests/tests.rs
jaq-syn/src/def.rs

This PR adds support for recursively defined filters with filter arguments.
For example:
~~~ jq
def repeat(f): f, repeat(f); repeat(1, 2)
~~~
(Note that you should not actually write `repeat` like this; even jq gives you quadratic runtime with that definition.)
Apart from this, this PR mostly rewrites MIR/LIR. Previously, LIR was a behemoth very hard to understand, which prevented further advances, such as tail-call optimisation. Now that road is open.
As a result of rewriting MIR/LIR, the compilation should now run in worst-case quadratic time, whereas before, it was exponential. Consider the following example:
~~~ jq
def d(f): f | empty, f | empty; d(d(d(d(d(d(d(d(d(d(d(d(d(d(d(d(d(d(d(d(d(0)))))))))))))))))))))
~~~
Before the PR, this took 2.5 seconds (on my AMD Ryzen 5 5500U), and for …

First-order recursive filters

---

jaq-interpret/src/filter.rs
jaq-interpret/src/lib.rs
jaq-interpret/src/lir.rs

Before this change, a filter AST referred to its sub-expressions by a `Box`.
After this change, a filter AST refers to its sub-expressions by an index into a `Vec`.
This is indispensable for implementing full tail-recursion optimisation (TCO) within the current API.
Consider the following example:
~~~ jq
def repeat(f): f, repeat(f); repeat(1, 2)
~~~
Here, when we call `repeat(f)` from within `repeat(f)`, we will want to return a value that is caught by the original call to `repeat(1, 2)`, and we want to pass this the information that we called it with the argument `f`.
However, because `f` was previously a pointer to a sub-expression, returning it would have needed adding a lifetime to the return value (`ValR`), which would have broken the API.
The new system also has the advantage that …

Save references to filter ASTs as integers, not as pointers

---

Cargo.lock
jaq-interpret/Cargo.toml
jaq-interpret/src/filter.rs
jaq-interpret/src/lib.rs
jaq-interpret/src/lir.rs
jaq-interpret/src/path.rs

This PR makes evaluation of object keys/values lazy.
Previously, the following filter would never yield a single result:
~~~ jq
'{("a", "b"): (0 | recurse(.+1)), ("c", "d"): 2}'
~~~
Now, it generates an infinite stream of objects, just like jq.
How's performance? Let's test it with the following filter:
~~~ jq
limit(1000000; {("a", "b"): (0 | recurse(.+1)), ("c", "d"): 2}) | empty
~~~
jq 1.7 takes 1.1 seconds, whereas jaq takes only 0.5 seconds! :)
As a bonus, this also eliminates the dependency of `jaq-interpret` on `itertools`.

Generate objects lazily & remove itertools dependency

---

jaq-core/src/lib.rs
jaq/src/main.rs

This PR adds the `env` filter. ~The `$ENV` global variable is not included in this PR yet, mostly because I didn't find a clean way of embedding it into global scope.~
It also adds the `$ENV` variable as an additional binding in the jaq CLI.
Reference: <https://jqlang.github.io/jq/manual/#$env-env>

Add env filter

---

Cargo.lock
jaq-core/Cargo.toml
jaq-core/src/lib.rs

This rewrites `group_by` to 1) terminate as soon as an error is encountered and to 2) remove the dependency on `itertools`.
The runtime of `group_by` slightly increases by about 4%:
~~~
$ hyperfine -L jq ./jaq-before,target/release/jaq,./jq-linux-amd64-1.7 '{jq} -n "[range(0; 1000000)] | group_by(. % 2) | empty"'
Benchmark 1: ./jaq-before -n "[range(0; 1000000)] | group_by(. % 2) | empty"
Time (mean ± σ):     492.0 ms ±   2.4 ms    [User: 411.1 ms, System: 80.6 ms]
Range (min … max):   487.0 ms … 494.9 ms    10 runs
Benchmark 2: target/release/jaq -n "[range(0; 1000000)] | group_by(. % 2) | empty"
Time (mean ± σ):     511.5 ms ±   1.5 ms    [User: 427.2 ms, System: 84.1 ms]
Range (min … max):   509.0 ms … 514.1 ms    10 runs
Benchmark 3: ./jq-linux-amd64-1.7 -n "[range(0; 1000000)] | …

Next-gen `group_by`

---

jaq-interpret/src/val.rs
jaq-interpret/tests/tests.rs

This PR implements `*` for objects, according to the spec here: <https://jqlang.github.io/jq/manual/#multiplication-division-modulo>

Recursive object merge

---

jaq-core/src/lib.rs
jaq-core/src/math.rs
jaq-core/tests/tests.rs
jaq-std/src/std.jq
jaq-std/tests/std.rs
jaq/src/main.rs

This PR delays the execution of many core filters.
For example, before this change, the filter `1, debug` printed:
~~~
[DEBUG] null
1
null
~~~
After this change, this prints:
~~~
1
[DEBUG] null
null
~~~
This is more consistent with jq, which yields:
~~~
1
["DEBUG:",null]
null
~~~
In some cases, this makes filters terminate which did not terminate before. For example,
~~~ jq
[0, 1] | first(1, sort_by(repeat(0)))
~~~
yielded no single output before, because `sort_by` was executed before 1 was yielded. With this PR, jaq yields 1 (just like jq).
Previously, also the `last/1` filter was executed strictly. With this PR, it is implemented by definition in a naturally lazy way.
This makes the `bf-fib` benchmark a bit slower (runtime decreases from 414.8 ms to 485.3 ms), but it remains still a lot …

Lazier core filters

---

jaq-interpret/src/filter.rs

The automatically derived `Default` implementation for `Owned` was incorrect, because it pointed to a non-existing filter AST. This made jaq crash when using `Owned::default`, as happened when not providing any filter at all (running `jaq` without any arguments).
Closes #146.

Correct `Default` implementation for `Owned` filters.

---

jaq/src/main.rs

Rename `--compact` to `--compact-output`, like in jq.

---

jaq-interpret/src/rc_lazy_list.rs

4999950000 overflows a usize (u32)

fix building jaq-interpret tests on 32-bit platforms

---

jaq-std/src/std.jq
jaq-std/tests/std.rs

This PR implements `indices` and copies jq's derivative implementations of `index` and `rindex` according to the spec [here](https://jqlang.github.io/jq/manual/#indices). Note that jq has TODO's related to performance on said implementations, so perhaps you'd want to close this PR and wait for a performant version of these filters.
~Also, the behaviour of jq's `indices` varies slightly when dealing with strings. I reported/asked about it here: <https://github.com/jqlang/jq/issues/3030>~ (my mistake; jq solved the issue in 1.7)
Closes #154

Implement indices, index and rindex.

---

jaq-core/src/lib.rs
jaq-core/tests/tests.rs
jaq-std/src/std.jq
jaq-std/tests/std.rs

This builds on the work of @kklingenberg #158 and replaces the definition of `indices` with a native implementation.

Implement `indices` natively.

---

Cargo.lock
jaq-core/Cargo.toml
jaq-core/src/lib.rs
jaq-core/tests/tests.rs
jaq-interpret/src/val.rs
jaq-interpret/tests/tests.rs
jaq-std/src/std.jq
jaq/Cargo.toml

This PR makes it possible to split a string `s` by `sep` via `s / sep`.
Previously, the same could be achieved by `s | split(sep)`.
Furthermore, the behaviour of `split` now matches jq, which returns `[]` when `s` is `""`. Before, `split` would return `[""]`.

String splitting via division.

---

jaq/src/main.rs

This PR allows loading files that cannot be memory-mapped. For example, before this PR, running `jaq . <(echo 1)` failed, whereas after this PR, it yields 1 as expected.
This should close <https://github.com/01mf02/jaq/issues/155>.

Fall back to regular file loading if memory mapping fails.

---

README.md

Since I found this tool by looking for `jq` on [Scoop](https://scoop.sh/), I thought it could be nice to add install instructions on Windows.
Scoop is sort of like Homebrew for Windows. The manifest auto-updates to the latest release from this repository.
You can find the manifest for it [here](https://github.com/ScoopInstaller/Main/blob/master/bucket/jaq.json).

Add Windows install (Scoop) instructions

---

Cargo.lock
jaq-play/Cargo.toml
jaq-play/src/lib.rs
jaq-play/src/style.css
jaq/Cargo.toml
jaq/src/main.rs

At the time of writing, the `ariadne` crate had [broken semantic versioning](https://github.com/zesterer/ariadne/issues/116) for over a month. This motivated my moving away from it to a newly-written crate called `codesnake`. Apart from having fewer dependencies and a significantly smaller code base, this crate enables colored parse error messages in jaq-play.
This should close https://github.com/01mf02/jaq/issues/176 as well as https://github.com/01mf02/jaq/issues/177.

Replace ariadne with codesnake

---

Cargo.lock

The newest mimalloc version contains a [patch](https://github.com/purpleprotocol/mimalloc_rust/commit/446fc231151cfab485b0ac7d5178baf797799dda) for building on the armv6 target, present for example on Void Linux.

chore(deps): bump mimalloc dependency

---

Cargo.lock
jaq-core/Cargo.toml
jaq-core/src/time.rs
jaq-core/tests/tests.rs
jaq-std/tests/std.rs

The crate `time` does not build on Rust 1.80 for versions smaller than 0.3.36: https://github.com/time-rs/time/issues/681
Apart from the fact that I do not like packages stopping to build when *updating* the compiler, updating time to 0.3.36 would require raising MSRV to 1.67, which I do not like.
I found that the `chrono` crate has a lower MSRV, it works fine on all compiler versions I tried, and using it is considerably simpler for my use case, so this PR replaces `time` with `chrono`. 
A small side effect of this is that jaq outputs fractional seconds with 6 digits instead of 9 before.

Use `chrono` instead of `time`.

---

README.md

IPA pronunciation is more straightforward than "like <word>", especially for non-native English speakers who do not know how to pronounce every French word in English.

docs: Add IPA pronunciation

---

jaq-core/src/compile.rs
jaq-core/src/lib.rs
jaq-core/src/load/mod.rs
jaq-core/src/load/parse.rs
jaq-core/tests/common/mod.rs
jaq-json/tests/common/mod.rs
jaq-play/src/lib.rs
jaq-std/tests/common/mod.rs
jaq/src/main.rs

This PR implements the `-L` command-line option and considers metadata of the shape {..., search: s, ...} attached to import/include directives. This applies to both module and data loading.

Consider metadata during file loading 

---

README.md
jaq-std/src/lib.rs
jaq-std/tests/funs.rs

Trims leading and trailing whitespace.
Was added to jq in https://github.com/jqlang/jq/pull/3056

Add `trim/0`, `ltrim/0` and `rtrim/0`

---

README.md

- `[[]] | implode` crash was fixed in 1.7 by https://github.com/jqlang/jq/pull/2646
- `[limit(0; 1, 2, 3)]` yielding 1,2 instead of nothing fixed in 1.7 by https://github.com/jqlang/jq/issues/2316
- `limit/2` will throw error on negative limit once https://github.com/jqlang/jq/pull/3181 is merged

Update on surprising jq behaviours

---

jaq-core/src/box_iter.rs
jaq-core/src/compile.rs
jaq-core/src/filter.rs
jaq-core/src/fold.rs
jaq-core/src/lib.rs
jaq-core/src/load/parse.rs
jaq-core/src/path.rs
jaq-core/src/val.rs
jaq-core/tests/tests.rs
jaq-std/src/lib.rs

This PR adds support for patterns in variable bindings, e.g. `. as {a: [$x, {("b", "c"): $y, $z}]} | $x, $y, $z`.
This also works in `foreach` and `reduce`.
Compared to jq, this also allows indexing with integers, e.g. `{(0): $x, (1): $y}`, which is equivalent to `[$x, $y]`. This can be useful if you wish to destructure arrays, but not necessarily the starting items.
However, jaq does not support the (undocumented) syntax `{$x: ...}`; for example, the filter `{x: [1]} as {$x: [$y]} | $x, $y` this yields `[1]` and `1` in jq.

Patterns in variable bindings.

---

jaq-core/src/filter.rs

I discovered the need for this via `cargo run -- -n '2 | recurse(. * 2)'`:
This panics at some point because of an integer overflow, but most interestingly, its last output is 2305843009213693952, not 4611686018427387904, which is the largest power of two that can be put into an i64.
That means that some operations, such as arithmetic, are performed *before* some previous values have been output.
I then found out that even `., (. + 1 | .)` calculates `. + 1` *before* outputting the input value (`.`).
After this PR, jaq should only run `filter.run(...)` for a filter whose output is used for evaluating the immediately next output value.
This PR could make it possible to evaluate a lot more things eagerly, where we use `once_with` today.

Lazy concatenation

---

jaq-core/src/box_iter.rs
jaq-core/src/compile.rs
jaq-core/src/lib.rs
jaq-core/tests/tests.rs
jaq/src/main.rs
jaq/tests/a.jq
jaq/tests/golden.rs

In #216, @wader found an expression `t` that would not yield the same result as `t | .`.
This boiled down to a bug in tail-call optimisation (TCO).
This PR corrects this bug. At the same time, it makes compilation more efficient, in particular when there are many definitions, variables, or labels. For example:
~~~
$ (echo 'def a: 1;'; for i in `seq 100000`; do echo 'def b: a;'; done; echo b) > bla.jq
$ jaq -n -f bla.jq
1
~~~
Previously, this would have taken quadratic time (with increasing values of `seq ...`); now, this takes n * log n time.
On the downside, the startup time becomes slightly longer for very small programs.
~~~
$ ./bench.sh target/release/jaq-tco-*
{"name": "empty", "n": 512, "time": {"target/release/jaq-tco-bug": [0.28], "target/release/jaq-tco-fix": [0.32]}}
{"name": …

Correct tail recursion & improve compiler complexity

---

jaq-core/src/box_iter.rs
jaq-core/tests/tests.rs
jaq-std/tests/funs.rs

This is an optimisation that allows the estimation of the number of outputs of calls to functions (both definitions and natively implemented ones).
It has quite positive results on many commonly used functions, see the benchmark results.
Here, `jaq-fmt-lazy` is before this PR and `jaq-fmt-strict` is after this PR:
~~~
{"name": "empty", "n": 512, "time": {"./jaq-fmt-lazy": [0.34], "./jaq-fmt-strict": [0.37]}}
{"name": "bf-fib", "n": 13, "time": {"./jaq-fmt-lazy": [0.51], "./jaq-fmt-strict": [0.49]}}
{"name": "defs", "n": 100000, "time": {"./jaq-fmt-lazy": [0.05], "./jaq-fmt-strict": [0.05]}}
{"name": "reduce-update", "n": 16384, "time": {"./jaq-fmt-lazy": [0.01, 0.01, 0.01], "./jaq-fmt-strict": [0.01, 0.01, 0.01]}}
{"name": "reverse", "n": 1048576, "time": {"./jaq-fmt-lazy": [0.09, 0.08, …

Make `flat_map_then` strict.

---

jaq-core/src/compile.rs
jaq-core/src/lib.rs
jaq-core/src/load/mod.rs
jaq-core/tests/common/mod.rs
jaq-json/tests/common/mod.rs
jaq-play/src/lib.rs
jaq-std/tests/common/mod.rs
jaq/src/main.rs

This PR allows providing paths on the command-line that are not UTF-8, see #231.
To see this in action:
~~~ bash
mkdir foo
echo bar > foo/$(iconv -f UTF-8 -t UTF-16 <(echo 'abc#$%%^'))
cargo run -- -n --rawfile a foo/* '$a'
~~~
This should yield `"bar\n"`. Before this PR, this would fail with:
~~~
error: Invalid UTF-8 was detected in one or more arguments
~~~

Enable jaq to deal with non-UTF-8 file paths (on the command-line).

---

README.md
jaq-core/src/load/mod.rs
jaq/src/main.rs

As a bonus, jaq now also uses the default search paths `["~/.jq", "$ORIGIN/../lib/jq", "$ORIGIN/../lib"]`.

Interpret search paths via -L as relative to working directory

---

Cargo.lock
jaq-json/Cargo.toml
jaq-json/src/lib.rs

This change replaces the hasher used in `jaq-json` with `foldhash`.
My personal motivation is that `foldhash` seems to be entering the ecosystem as an upcoming state-of-the-art, but there are other considerations:
- The original motivation for `ahash` way back in 0.5.0 was https://github.com/01mf02/jaq/commit/6114f309a066f33481f4d276dcd11c109ac87af9 and now `foldhash` has zero runtime dependencies, which allows dropping `zerocopy` from `Cargo.lock`
- Benchmarks show that `foldhash` is at worst comparable to `ahash`, so no apparent perf harm in the replacement
I am aware that this change might feel insubstantial or arbitrary, so please treat it as a loose suggestion and feel free to close immediately if uninterested :)

perf: switch jaq-json hasher to foldhash

---

Cargo.lock
jaq/Cargo.toml
jaq/src/cli.rs
jaq/src/help.txt
jaq/src/main.rs

The motivation is to correctly parse `--args`. As a nice side effect, this eliminates the dependency on clap as well. See: <https://github.com/01mf02/jaq/issues/216#issuecomment-2480317387>

Rewrite command-line argument parser by hand.

---

jaq-core/src/compile.rs
jaq-core/src/filter.rs
jaq-core/src/fold.rs

This PR unifies the logic behind the execution of `reduce` and `foreach`.
Furthermore, it turns a panic on updating with unsupported operators into an error that can be caught.

Unify folding operators.

---

jaq/src/cli.rs

`--null-input` long form flag is currently mapped to the wrong short form flag:
```
❯ jaq --version
jaq 2.0.0
❯ jaq --null-input '.'
Error: unknown flag: -N
❯ jaq -n '.'
null
```

Fix --null-input flag

---

jaq/src/main.rs

`--slurpfile` is currently silently ignored due to a small typo:
```
❯ jaq --version
jaq 2.0.0
❯ jaq --slurpfile foo <(echo 1) -n '$foo'
Error: undefined variable
╭─[<inline>]
│
1 │ $foo
┆ ──┬─
┆   │
┆   ╰── undefined variable
──╯
```

Fix --slurpfile flag

---

README.md
jaq-json/src/lib.rs
jaq-std/src/defs.jq
jaq-std/tests/defs.rs

This aligns jaq's and jq's handling of NaN (not a number), by enforcing `nan < nan`.
Before this change, it could happen that operations that yielded `nan` could have introduced non-deterministic behaviour, see #243. With this PR, the non-deterministic floating-point behaviour is still there, but it should not be observable anymore.

NaN compatibility

---

jaq-core/src/load/mod.rs

With this minor tweak, I can use `Import<&'s str, &'s str>`, which is useful when all file references live in a HashMap or similar structure.

jaq-core/loader: be specific about input parameter for reader

---

jaq/src/cli.rs
jaq/src/help.txt
jaq/src/main.rs
jaq/tests/golden.rs

Add --argjson support

---

jaq-json/src/lib.rs
jaq-play/src/lib.rs
jaq/src/main.rs
jaq/tests/golden.rs

This should address <https://github.com/01mf02/jaq/issues/209#issuecomment-2645713323>.

Correct printing of special Unicode characters in objects keys.

---

jaq-core/src/compile.rs
jaq-core/src/exn.rs
jaq-core/src/filter.rs
jaq-core/src/lib.rs
jaq-core/tests/tests.rs

The offset mechanism previously used to deal with `label ... break` yielded wrong outputs in certain situations. For example, `label $x | (def x: break $x; (label $y | x), 0)` yields `0` in jaq 2.1.0, whereas it should yield `empty` (like jq).
This PR replaces the offset mechanism completely by a substitution mechanism that assigns break labels a unique index on the current execution path. This uses to a large extent the existing infrastructure for variables. Consequently, this corrects the execution of `label ... break` expressions.
I discovered this issue while reworking the [formal jq specification](https://github.com/01mf02/jq-lang-spec/).

Handle break labels like variables.

---

jaq/src/main.rs

In #136, @JustinAzoff remarked that output throughput can be increased by buffering, when the output device is not a terminal (TTY). This PR implements that strategy.

Buffer write operations when stdout is not a terminal.

---

jaq-core/src/filter.rs
jaq-core/tests/tests.rs

This PR enables updates with folding operators (`reduce` and `foreach`) on the left-hand side of updates.
This is something that jq cannot currently do.
The motivating case for this PR was the implementation of `getpath`. In jq, we can use `getpath` on the left-hand side of updates:
~~~
$ jq -nc '[[2, 3]] | getpath([0, 1]) += 1'
[[2,4]]
~~~
In jq, `getpath` is a builtin filter implemented in C.
In jaq, I tried to first implement `getpath` as definition, as such:
~~~ jq
def getpath($p): if $p != [] then .[$p[0]] | getpath($p[1:]) end;
~~~
This is a more convoluted version of the following:
~~~ jq
def getpath($path): reduce $path[] as $p (.; .[$p]);
~~~
The difference between the two versions is that the first version can be used on the left-hand side of updates, whereas the second version …

Implement updates with folding operators (reduce/foreach) on LHS.

---

jaq-core/src/compile.rs
jaq-core/src/filter.rs

This change simplifies the compilation of `try`-`catch` filters and should speed up their execution, at the cost of slightly more complex execution logic.

Implement `try`-`catch` without `label $x | ...`.

---

jaq-core/src/filter.rs
jaq-std/tests/funs.rs

Before, when a new label was declared inside a native function argument, breaking to a label declared outside the call to the native function could be caught by the wrong label.
As example, consider the following filter:
~~~ jq
[1, 2] | label $x | sort_by(label $y | break $x)
~~~
Before this change, this would (erroneously) yield `[1, 2]`. After this change, this (correctly) yields no output at all.

Correctly handle labels inside of native function arguments

---

jaq/src/main.rs

Hey there, here's the fix for persisting files using the in-place option on Windows. This will ensure that the file handle used for processing of the file will be released before persisting to disk from the temp directory.
See output below:
```
~\source\jaq on  avoid-open-handles-during-persist [?] via 🦀 v1.88.0 took 3s
🕙 [ 09:48:19 AM ] ❯ git co main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
~\source\jaq on  main [?] via 🦀 v1.88.0
🕙 [ 09:48:26 AM ] ❯ cp ..\firefox-settings\bookmarks.json .
~\source\jaq on  main [?] via 🦀 v1.88.0
🕙 [ 09:48:31 AM ] ❯ cargo run -- -i . bookmarks.json
Compiling jaq v2.2.0 (C:\Users\Fots\source\jaq\jaq)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.30s
Running `target\debug\jaq.exe -i . bookmarks.json`
Error: …
```

Ensure no file handles remain open during in-place persist (closes #292).

---

.github/workflows/msrv.yml
Cargo.lock
README.md
jaq/Cargo.toml
jaq/src/filter.rs
jaq/src/main.rs
jaq/src/read.rs
jaq/src/repl.rs
jaq/src/write.rs

This PR implements a REPL akin to [fq's REPL](https://github.com/wader/fq/blob/master/doc/usage.md#interactive-repl---repl-i), namely as a filter called `repl`.
REPL usage can be nested, as demonstrated below:
~~~
$ jaq -n repl
> .
null
> .+1
1
> .+1 | repl
> .
1
> ^D
> .
null
> ^D
$
~~~
Unlike `fq`, jaq does not require a `--repl` flag, and the `repl` filter can be used anywhere, not just "last in pipeline".
Due to depending on `rustyline` for implementing the REPL, this requires bumping MSRV to 1.66.
- Nested REPLs cannot access variables from parent REPLs (like in `fq`).
- ~~The indentation does not increase for nested REPLs.~~ This has been implemented in [1e35912](https://github.com/01mf02/jaq/pull/303/commits/1e35912172eb17514fc349b89e61ac268aba15f5).
- Only terms can be input; that …

Implement `repl` filter and split up main file

---

README.md
jaq-json/src/defs.jq
jaq-json/tests/funs.rs

Previously, passing a string representation of anything to `tonumber` would succeed; now it actually has to be a number or a string parseable as a number.
Added the missing `toboolean` while we're in the vicinity.
Includes tests.

add toboolean/0 and error handling for conversions

---

jaq-core/examples/parse.rs

This is used by the toy interpreter [`ujq`](https://github.com/01mf02/jq-lang-spec/tree/main/ujq).

Add parsing example

---

Cargo.lock
jaq-json/src/json.rs
jaq-json/src/lib.rs
jaq-json/src/num.rs

This PR uses a new feature of `hifijson` to simplify and speed up parsing of negative decimal numbers.
Negating a `jaq_json::Num::Dec(_)` is relatively costly, because it allocates a new string and a new `Rc` pointer. Since #327, jaq performed such a negation whenever a negative decimal number was parsed. Now, parsing does not rely on negating an existing `Num`, but creates the correct `Num` from the start.

Avoid allocation when parsing negative decimal numbers

---

jaq-json/src/lib.rs
jaq-std/src/lib.rs
jaq-std/src/math.rs
jaq-std/src/time.rs

This makes it clear that `as_f64` can fail in only one way, namely if a value is not a number.

Simplify type of `as_f64` and introduce `try_as_f64`

---

jaq-core/src/compile.rs
jaq/src/main.rs

This removal is intended to resolve unintentional crashes as observed in https://github.com/01mf02/jaq/issues/323#issuecomment-3333517132.

Delete `Default` implementation for `Lut`
